markdown: kramdown
url: ''
baseurl: null
title: Bhanu Teja Kurakula
description: Third Year Undergraduate Student and Data Science Enthusiast
site-image: >-
  https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
site-keywords: Portfolio Website
favicon-url: 'null'
heroimage: ''
email: k.bhanuteja2001@gmail.com
facebook_username: bhanu.teja.5209
twitter_username: bhanutejakurak1
instagram_username: knightlight193
linkedin_username: bhanutejakurakula
github_username: bhanuteja2001
youtube_channel_id: ''
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /
google-analytics: G-5EGG6GP8BV
disqus-shortname: thedevslot
author-name: TheDevsLot
author-image: >-
  https://media-exp1.licdn.com/dms/image/C5603AQGlZMDZGKKKMA/profile-displayphoto-shrink_200_200/0?e=1602720000&v=beta&t=AGFIDX667X0ARULoI69H9O5vPEnxwYXl0akGYqOsNkY
author-about: >-
  A Third year Undergraduate Electronics Student at Amrita Vishwa Vidyapeetham
  with an interest in Data Science and MLOps. Having work experience in Web
  Designing.
author-url: 'https://github.com/bhanuteja2001'
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-admin
  - jekyll-feed
permalink: 'blog/:title'
compress_html:
  clippings: all
defaults:
  - scope:
      type: posts
    values:
      layout: post
      post-image: ''
      description: ''
      tags:
        - ''
  - scope:
      type: pages
    values:
      layout: page
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
